### ISSUE TITLE
Enable to publish a release from github action.

### ISSUE THREAD

**Issue by cocuh** [google/assertor#83]

**Comment by tisonkun** [comment]
I can help in this issue, as long as you set up the token for cargo publish.

Here is how we did it for Apache OpenDAL:

https://github.com/apache/opendal/blob/5e735cc53cd8638f47bd10b67d5d6e258ff22b67/.github/workflows/release_rust.yml#L69-L84

Mainly, it's:

```
cargo publish --all-features --dry-run
cargo publish --all-features
```

... with  `CARGO_REGISTRY_TOKEN` set.

**Comment by cgruber** [comment]
Any news on this? The released crate (0.0.2) doesn't have the anyhow functionality, and I'd love to use it.

**Comment by cocuh** [comment]
Let me work on this tomorrow. Thank you for using!

**Comment by tisonkun** [comment]
Cool!

**Comment by cgruber** [comment]
I'm so glad to use it. I'm the original Google Truth author, so while I'm learning Rust, finding something inspired by it, so I can write tests in a familiar way, was very gratifying. Thank you so much for building this.

**Comment by cocuh** [comment]
Done.  Released a new version.

I expect future releases to be more frequent with a more lightweight release process.  (Sorry for no recent release!)

Thank you very much for using this!  And a huge thank you for your work in establishing human-friendly assertion in Google Truth.  Without it, this project would not have happened.
